# Generated by Django 3.2.9 on 2021-11-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lockers',
            fields=[
                ('lockernum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('written_lockernum', models.IntegerField(default='0')),
                ('floor', models.IntegerField(default=1)),
                ('reserved', models.IntegerField(default=0)),
                ('sector', models.CharField(default='A', help_text='층별 구역', max_length=2)),
                ('building', models.CharField(choices=[('HN', '형남공학관'), ('IS', '정보과학관'), ('CB', '문화관')], default='IS', max_length=6)),
                ('department', models.CharField(choices=[('CS', '컴퓨터학부'), ('GM', '글로벌미디어학부'), ('EIE', '전자정보공학부'), ('SW', '소프트웨어학부'), ('AIC', 'AI융합학부')], default='CS', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='이름', max_length=10)),
                ('id', models.CharField(help_text='학번', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(choices=[('CS', '컴퓨터학부'), ('GM', '글로벌미디어학부'), ('EIE', '전자정보공학부'), ('SW', '소프트웨어학부'), ('AIC', 'AI융합학부')], default='CS', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('lockernum', models.ForeignKey(db_column='lockernum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockerusing', to='locker.lockers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
