# Generated by Django 4.0 on 2022-01-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockers',
            old_name='locker_department',
            new_name='department',
        ),
    ]
