# Generated by Django 4.0.1 on 2022-01-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_rename_locker_department_lockers_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
