# Generated by Django 3.2.9 on 2021-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20211114_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='lockernum',
            field=models.IntegerField(null=True),
        ),
    ]
