# Generated by Django 4.0.1 on 2022-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
