# Generated by Django 4.0.1 on 2022-02-06 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_department_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fintime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 16, 33, 18, 233299), help_text='예약 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='department',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 16, 33, 18, 233281), help_text='예약시작날짜'),
        ),
    ]
