# Generated by Django 4.0.1 on 2022-03-07 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_alter_department_fintime_alter_department_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='fintime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 19, 57, 9, 530379), help_text='예약 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='department',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 19, 57, 9, 530361), help_text='예약시작날짜'),
        ),
    ]
