# Generated by Django 4.0.1 on 2022-02-28 22:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_alter_department_fintime_alter_department_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='fintime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 22, 56, 36, 123314), help_text='예약 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='department',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 56, 36, 123296), help_text='예약시작날짜'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
