# Generated by Django 4.0.1 on 2022-03-06 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_alter_department_fintime_alter_department_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='fintime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 37, 7, 363697), help_text='예약 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='department',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 22, 37, 7, 363662), help_text='예약시작날짜'),
        ),
        migrations.AlterField(
            model_name='lockers',
            name='building',
            field=models.CharField(choices=[('05', '형남공학관'), ('21', '정보과학관')], default='IS', max_length=6),
        ),
    ]
