FROM python:3.10.0
WORKDIR /lockerweb

#PACKAGE INSTALL
COPY requirements.txt ./
RUN apt update
RUN apt-get install python3-dev default-libmysqlclient-dev build-essential
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["gunicorn","--bind","0.0.0.0:8080","ssulocker.wsgi.application"]